// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "conv2d.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic conv2d::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic conv2d::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<20> conv2d::ap_ST_fsm_state1 = "1";
const sc_lv<20> conv2d::ap_ST_fsm_state2 = "10";
const sc_lv<20> conv2d::ap_ST_fsm_state3 = "100";
const sc_lv<20> conv2d::ap_ST_fsm_state4 = "1000";
const sc_lv<20> conv2d::ap_ST_fsm_state5 = "10000";
const sc_lv<20> conv2d::ap_ST_fsm_state6 = "100000";
const sc_lv<20> conv2d::ap_ST_fsm_state7 = "1000000";
const sc_lv<20> conv2d::ap_ST_fsm_state8 = "10000000";
const sc_lv<20> conv2d::ap_ST_fsm_state9 = "100000000";
const sc_lv<20> conv2d::ap_ST_fsm_state10 = "1000000000";
const sc_lv<20> conv2d::ap_ST_fsm_state11 = "10000000000";
const sc_lv<20> conv2d::ap_ST_fsm_state12 = "100000000000";
const sc_lv<20> conv2d::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<20> conv2d::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<20> conv2d::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<20> conv2d::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<20> conv2d::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<20> conv2d::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<20> conv2d::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<20> conv2d::ap_ST_fsm_state20 = "10000000000000000000";
const sc_lv<32> conv2d::ap_const_lv32_2 = "10";
const sc_lv<1> conv2d::ap_const_lv1_0 = "0";
const sc_lv<32> conv2d::ap_const_lv32_4 = "100";
const sc_lv<1> conv2d::ap_const_lv1_1 = "1";
const sc_lv<32> conv2d::ap_const_lv32_12 = "10010";
const sc_lv<32> conv2d::ap_const_lv32_13 = "10011";
const int conv2d::C_S_AXI_DATA_WIDTH = "100000";
const sc_lv<32> conv2d::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> conv2d::ap_const_lv32_1 = "1";
const sc_lv<32> conv2d::ap_const_lv32_3 = "11";
const sc_lv<32> conv2d::ap_const_lv32_5 = "101";
const sc_lv<32> conv2d::ap_const_lv32_6 = "110";
const sc_lv<32> conv2d::ap_const_lv32_7 = "111";
const sc_lv<32> conv2d::ap_const_lv32_8 = "1000";
const sc_lv<32> conv2d::ap_const_lv32_9 = "1001";
const sc_lv<32> conv2d::ap_const_lv32_B = "1011";
const sc_lv<32> conv2d::ap_const_lv32_F = "1111";
const sc_lv<32> conv2d::ap_const_lv32_10 = "10000";
const sc_lv<32> conv2d::ap_const_lv32_11 = "10001";
const sc_lv<2> conv2d::ap_const_lv2_0 = "00";
const sc_lv<31> conv2d::ap_const_lv31_0 = "0000000000000000000000000000000";
const sc_lv<32> conv2d::ap_const_lv32_C = "1100";
const sc_lv<32> conv2d::ap_const_lv32_A = "1010";
const sc_lv<2> conv2d::ap_const_lv2_3 = "11";
const sc_lv<2> conv2d::ap_const_lv2_1 = "1";
const sc_lv<31> conv2d::ap_const_lv31_1 = "1";
const sc_lv<6> conv2d::ap_const_lv6_0 = "000000";
const sc_lv<32> conv2d::ap_const_lv32_FFFFFFFE = "11111111111111111111111111111110";
const sc_lv<32> conv2d::ap_const_lv32_FFFFFFFD = "11111111111111111111111111111101";
const bool conv2d::ap_const_boolean_1 = true;

conv2d::conv2d(sc_module_name name) : sc_module(name), mVcdFile(0) {
    conv2d_AXILiteS_s_axi_U = new conv2d_AXILiteS_s_axi<C_S_AXI_AXILITES_ADDR_WIDTH,C_S_AXI_AXILITES_DATA_WIDTH>("conv2d_AXILiteS_s_axi_U");
    conv2d_AXILiteS_s_axi_U->AWVALID(s_axi_AXILiteS_AWVALID);
    conv2d_AXILiteS_s_axi_U->AWREADY(s_axi_AXILiteS_AWREADY);
    conv2d_AXILiteS_s_axi_U->AWADDR(s_axi_AXILiteS_AWADDR);
    conv2d_AXILiteS_s_axi_U->WVALID(s_axi_AXILiteS_WVALID);
    conv2d_AXILiteS_s_axi_U->WREADY(s_axi_AXILiteS_WREADY);
    conv2d_AXILiteS_s_axi_U->WDATA(s_axi_AXILiteS_WDATA);
    conv2d_AXILiteS_s_axi_U->WSTRB(s_axi_AXILiteS_WSTRB);
    conv2d_AXILiteS_s_axi_U->ARVALID(s_axi_AXILiteS_ARVALID);
    conv2d_AXILiteS_s_axi_U->ARREADY(s_axi_AXILiteS_ARREADY);
    conv2d_AXILiteS_s_axi_U->ARADDR(s_axi_AXILiteS_ARADDR);
    conv2d_AXILiteS_s_axi_U->RVALID(s_axi_AXILiteS_RVALID);
    conv2d_AXILiteS_s_axi_U->RREADY(s_axi_AXILiteS_RREADY);
    conv2d_AXILiteS_s_axi_U->RDATA(s_axi_AXILiteS_RDATA);
    conv2d_AXILiteS_s_axi_U->RRESP(s_axi_AXILiteS_RRESP);
    conv2d_AXILiteS_s_axi_U->BVALID(s_axi_AXILiteS_BVALID);
    conv2d_AXILiteS_s_axi_U->BREADY(s_axi_AXILiteS_BREADY);
    conv2d_AXILiteS_s_axi_U->BRESP(s_axi_AXILiteS_BRESP);
    conv2d_AXILiteS_s_axi_U->ACLK(ap_clk);
    conv2d_AXILiteS_s_axi_U->ARESET(ap_rst_n_inv);
    conv2d_AXILiteS_s_axi_U->ACLK_EN(ap_var_for_const0);
    conv2d_AXILiteS_s_axi_U->input_row(input_row);
    conv2d_AXILiteS_s_axi_U->input_col(input_col);
    input_U = new conv2d_input("input_U");
    input_U->clk(ap_clk);
    input_U->reset(ap_rst_n_inv);
    input_U->address0(input_address0);
    input_U->ce0(input_ce0);
    input_U->we0(input_we0);
    input_U->d0(stream_input_TDATA_int);
    input_U->q0(input_q0);
    kernel_U = new conv2d_kernel("kernel_U");
    kernel_U->clk(ap_clk);
    kernel_U->reset(ap_rst_n_inv);
    kernel_U->address0(kernel_address0);
    kernel_U->ce0(kernel_ce0);
    kernel_U->we0(kernel_we0);
    kernel_U->d0(stream_kernel_TDATA_int);
    kernel_U->q0(kernel_q0);
    output_U = new conv2d_output("output_U");
    output_U->clk(ap_clk);
    output_U->reset(ap_rst_n_inv);
    output_U->address0(output_address0);
    output_U->ce0(output_ce0);
    output_U->we0(output_we0);
    output_U->d0(output_d0);
    output_U->q0(output_q0);
    conv2d_fadd_32ns_bkb_U1 = new conv2d_fadd_32ns_bkb<1,4,32,32,32>("conv2d_fadd_32ns_bkb_U1");
    conv2d_fadd_32ns_bkb_U1->clk(ap_clk);
    conv2d_fadd_32ns_bkb_U1->reset(ap_rst_n_inv);
    conv2d_fadd_32ns_bkb_U1->din0(empty_8_reg_282);
    conv2d_fadd_32ns_bkb_U1->din1(x_reg_916);
    conv2d_fadd_32ns_bkb_U1->ce(ap_var_for_const0);
    conv2d_fadd_32ns_bkb_U1->dout(grp_fu_327_p2);
    conv2d_fmul_32ns_cud_U2 = new conv2d_fmul_32ns_cud<1,2,32,32,32>("conv2d_fmul_32ns_cud_U2");
    conv2d_fmul_32ns_cud_U2->clk(ap_clk);
    conv2d_fmul_32ns_cud_U2->reset(ap_rst_n_inv);
    conv2d_fmul_32ns_cud_U2->din0(input_load_reg_906);
    conv2d_fmul_32ns_cud_U2->din1(kernel_load_reg_911);
    conv2d_fmul_32ns_cud_U2->ce(ap_var_for_const0);
    conv2d_fmul_32ns_cud_U2->dout(grp_fu_333_p2);
    regslice_both_stream_kernel_V_data_U = new regslice_both<32>("regslice_both_stream_kernel_V_data_U");
    regslice_both_stream_kernel_V_data_U->ap_clk(ap_clk);
    regslice_both_stream_kernel_V_data_U->ap_rst(ap_rst_n_inv);
    regslice_both_stream_kernel_V_data_U->data_in(stream_kernel_TDATA);
    regslice_both_stream_kernel_V_data_U->vld_in(stream_kernel_TVALID);
    regslice_both_stream_kernel_V_data_U->ack_in(regslice_both_stream_kernel_V_data_U_ack_in);
    regslice_both_stream_kernel_V_data_U->data_out(stream_kernel_TDATA_int);
    regslice_both_stream_kernel_V_data_U->vld_out(stream_kernel_TVALID_int);
    regslice_both_stream_kernel_V_data_U->ack_out(stream_kernel_TREADY_int);
    regslice_both_stream_kernel_V_data_U->apdone_blk(regslice_both_stream_kernel_V_data_U_apdone_blk);
    regslice_both_w1_stream_kernel_V_last_U = new regslice_both_w1<1>("regslice_both_w1_stream_kernel_V_last_U");
    regslice_both_w1_stream_kernel_V_last_U->ap_clk(ap_clk);
    regslice_both_w1_stream_kernel_V_last_U->ap_rst(ap_rst_n_inv);
    regslice_both_w1_stream_kernel_V_last_U->data_in(stream_kernel_TLAST);
    regslice_both_w1_stream_kernel_V_last_U->vld_in(stream_kernel_TVALID);
    regslice_both_w1_stream_kernel_V_last_U->ack_in(regslice_both_w1_stream_kernel_V_last_U_ack_in);
    regslice_both_w1_stream_kernel_V_last_U->data_out(stream_kernel_TLAST_int);
    regslice_both_w1_stream_kernel_V_last_U->vld_out(regslice_both_w1_stream_kernel_V_last_U_vld_out);
    regslice_both_w1_stream_kernel_V_last_U->ack_out(stream_kernel_TREADY_int);
    regslice_both_w1_stream_kernel_V_last_U->apdone_blk(regslice_both_w1_stream_kernel_V_last_U_apdone_blk);
    regslice_both_stream_input_V_data_U = new regslice_both<32>("regslice_both_stream_input_V_data_U");
    regslice_both_stream_input_V_data_U->ap_clk(ap_clk);
    regslice_both_stream_input_V_data_U->ap_rst(ap_rst_n_inv);
    regslice_both_stream_input_V_data_U->data_in(stream_input_TDATA);
    regslice_both_stream_input_V_data_U->vld_in(stream_input_TVALID);
    regslice_both_stream_input_V_data_U->ack_in(regslice_both_stream_input_V_data_U_ack_in);
    regslice_both_stream_input_V_data_U->data_out(stream_input_TDATA_int);
    regslice_both_stream_input_V_data_U->vld_out(stream_input_TVALID_int);
    regslice_both_stream_input_V_data_U->ack_out(stream_input_TREADY_int);
    regslice_both_stream_input_V_data_U->apdone_blk(regslice_both_stream_input_V_data_U_apdone_blk);
    regslice_both_w1_stream_input_V_last_U = new regslice_both_w1<1>("regslice_both_w1_stream_input_V_last_U");
    regslice_both_w1_stream_input_V_last_U->ap_clk(ap_clk);
    regslice_both_w1_stream_input_V_last_U->ap_rst(ap_rst_n_inv);
    regslice_both_w1_stream_input_V_last_U->data_in(stream_input_TLAST);
    regslice_both_w1_stream_input_V_last_U->vld_in(stream_input_TVALID);
    regslice_both_w1_stream_input_V_last_U->ack_in(regslice_both_w1_stream_input_V_last_U_ack_in);
    regslice_both_w1_stream_input_V_last_U->data_out(stream_input_TLAST_int);
    regslice_both_w1_stream_input_V_last_U->vld_out(regslice_both_w1_stream_input_V_last_U_vld_out);
    regslice_both_w1_stream_input_V_last_U->ack_out(stream_input_TREADY_int);
    regslice_both_w1_stream_input_V_last_U->apdone_blk(regslice_both_w1_stream_input_V_last_U_apdone_blk);
    regslice_both_stream_output_V_data_U = new regslice_both<32>("regslice_both_stream_output_V_data_U");
    regslice_both_stream_output_V_data_U->ap_clk(ap_clk);
    regslice_both_stream_output_V_data_U->ap_rst(ap_rst_n_inv);
    regslice_both_stream_output_V_data_U->data_in(output_q0);
    regslice_both_stream_output_V_data_U->vld_in(stream_output_TVALID_int);
    regslice_both_stream_output_V_data_U->ack_in(stream_output_TREADY_int);
    regslice_both_stream_output_V_data_U->data_out(stream_output_TDATA);
    regslice_both_stream_output_V_data_U->vld_out(regslice_both_stream_output_V_data_U_vld_out);
    regslice_both_stream_output_V_data_U->ack_out(stream_output_TREADY);
    regslice_both_stream_output_V_data_U->apdone_blk(regslice_both_stream_output_V_data_U_apdone_blk);
    regslice_both_w1_stream_output_V_last_U = new regslice_both_w1<1>("regslice_both_w1_stream_output_V_last_U");
    regslice_both_w1_stream_output_V_last_U->ap_clk(ap_clk);
    regslice_both_w1_stream_output_V_last_U->ap_rst(ap_rst_n_inv);
    regslice_both_w1_stream_output_V_last_U->data_in(stream_output_TLAST_int);
    regslice_both_w1_stream_output_V_last_U->vld_in(stream_output_TVALID_int);
    regslice_both_w1_stream_output_V_last_U->ack_in(regslice_both_w1_stream_output_V_last_U_ack_in_dummy);
    regslice_both_w1_stream_output_V_last_U->data_out(stream_output_TLAST);
    regslice_both_w1_stream_output_V_last_U->vld_out(regslice_both_w1_stream_output_V_last_U_vld_out);
    regslice_both_w1_stream_output_V_last_U->ack_out(stream_output_TREADY);
    regslice_both_w1_stream_output_V_last_U->apdone_blk(regslice_both_w1_stream_output_V_last_U_apdone_blk);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln31_fu_396_p2);
    sensitive << ( sub_ln31_reg_782 );
    sensitive << ( zext_ln31_2_fu_392_p1 );

    SC_METHOD(thread_add_ln43_fu_471_p2);
    sensitive << ( zext_ln43_cast_reg_806 );
    sensitive << ( trunc_ln43_fu_467_p1 );

    SC_METHOD(thread_add_ln60_fu_555_p2);
    sensitive << ( sub_ln60_reg_842 );
    sensitive << ( trunc_ln60_2_fu_551_p1 );

    SC_METHOD(thread_add_ln65_1_fu_641_p2);
    sensitive << ( trunc_ln65_1_fu_637_p1 );
    sensitive << ( zext_ln65_3_fu_633_p1 );

    SC_METHOD(thread_add_ln65_2_fu_647_p2);
    sensitive << ( sext_ln65_cast_reg_878 );
    sensitive << ( add_ln65_1_fu_641_p2 );

    SC_METHOD(thread_add_ln65_3_fu_661_p2);
    sensitive << ( sub_ln65_reg_883 );
    sensitive << ( zext_ln65_4_fu_657_p1 );

    SC_METHOD(thread_add_ln65_fu_585_p2);
    sensitive << ( trunc_ln65_fu_581_p1 );
    sensitive << ( zext_ln65_fu_577_p1 );

    SC_METHOD(thread_add_ln79_1_fu_531_p2);
    sensitive << ( input_col_read_reg_760 );

    SC_METHOD(thread_add_ln79_fu_526_p2);
    sensitive << ( input_row_read_reg_767 );

    SC_METHOD(thread_add_ln84_fu_750_p2);
    sensitive << ( sub_ln84_reg_939 );
    sensitive << ( trunc_ln84_2_fu_746_p1 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state16);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state17);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state18);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state19);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state20);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state3);
    sensitive << ( icmp_ln29_fu_371_p2 );
    sensitive << ( stream_kernel_TVALID_int );

    SC_METHOD(thread_ap_block_state5);
    sensitive << ( icmp_ln41_fu_447_p2 );
    sensitive << ( stream_input_TVALID_int );

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_col_4_fu_452_p2);
    sensitive << ( col_1_reg_224 );

    SC_METHOD(thread_col_5_fu_545_p2);
    sensitive << ( col_2_reg_247 );

    SC_METHOD(thread_col_6_fu_730_p2);
    sensitive << ( col_3_reg_316 );

    SC_METHOD(thread_col_boundary_fu_438_p2);
    sensitive << ( input_col_read_reg_760 );

    SC_METHOD(thread_col_fu_377_p2);
    sensitive << ( col_0_reg_202 );

    SC_METHOD(thread_icmp_ln28_fu_337_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( row_0_reg_191 );

    SC_METHOD(thread_icmp_ln29_fu_371_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln29_fu_371_p2 );
    sensitive << ( col_0_reg_202 );
    sensitive << ( stream_kernel_TVALID_int );

    SC_METHOD(thread_icmp_ln40_fu_410_p2);
    sensitive << ( input_row_read_reg_767 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( zext_ln40_fu_406_p1 );

    SC_METHOD(thread_icmp_ln41_fu_447_p2);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln41_fu_447_p2 );
    sensitive << ( input_col_read_reg_760 );
    sensitive << ( zext_ln41_fu_443_p1 );
    sensitive << ( stream_input_TVALID_int );

    SC_METHOD(thread_icmp_ln57_fu_485_p2);
    sensitive << ( row_boundary_reg_811 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( zext_ln57_fu_481_p1 );

    SC_METHOD(thread_icmp_ln58_fu_540_p2);
    sensitive << ( col_boundary_reg_817 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( zext_ln58_fu_536_p1 );

    SC_METHOD(thread_icmp_ln63_fu_565_p2);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( m_0_reg_271 );

    SC_METHOD(thread_icmp_ln64_fu_621_p2);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( n_0_reg_294 );

    SC_METHOD(thread_icmp_ln76_fu_675_p2);
    sensitive << ( row_boundary_reg_811 );
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( regslice_both_stream_output_V_data_U_apdone_blk );
    sensitive << ( zext_ln76_fu_671_p1 );

    SC_METHOD(thread_icmp_ln77_fu_725_p2);
    sensitive << ( col_boundary_reg_817 );
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( zext_ln77_fu_721_p1 );

    SC_METHOD(thread_icmp_ln79_1_fu_736_p2);
    sensitive << ( add_ln79_1_reg_852 );
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( icmp_ln77_fu_725_p2 );
    sensitive << ( zext_ln77_fu_721_p1 );

    SC_METHOD(thread_icmp_ln79_fu_686_p2);
    sensitive << ( add_ln79_reg_847 );
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( regslice_both_stream_output_V_data_U_apdone_blk );
    sensitive << ( icmp_ln76_fu_675_p2 );
    sensitive << ( zext_ln76_fu_671_p1 );

    SC_METHOD(thread_input_address0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( zext_ln43_fu_476_p1 );
    sensitive << ( sext_ln65_fu_652_p1 );

    SC_METHOD(thread_input_ce0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln41_fu_447_p2 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( stream_input_TVALID_int );

    SC_METHOD(thread_input_we0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln41_fu_447_p2 );
    sensitive << ( stream_input_TVALID_int );

    SC_METHOD(thread_kernel_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( sext_ln31_fu_401_p1 );
    sensitive << ( sext_ln65_1_fu_666_p1 );

    SC_METHOD(thread_kernel_ce0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln29_fu_371_p2 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( stream_kernel_TVALID_int );

    SC_METHOD(thread_kernel_we0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln29_fu_371_p2 );
    sensitive << ( stream_kernel_TVALID_int );

    SC_METHOD(thread_m_fu_571_p2);
    sensitive << ( m_0_reg_271 );

    SC_METHOD(thread_n_fu_627_p2);
    sensitive << ( n_0_reg_294 );

    SC_METHOD(thread_output_address0);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( output_addr_reg_865 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( sext_ln60_fu_560_p1 );
    sensitive << ( sext_ln84_fu_755_p1 );

    SC_METHOD(thread_output_ce0);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state18 );

    SC_METHOD(thread_output_d0);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( grp_fu_327_p2 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_output_we0);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( icmp_ln58_fu_540_p2 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_row_4_fu_343_p2);
    sensitive << ( row_0_reg_191 );

    SC_METHOD(thread_row_5_fu_415_p2);
    sensitive << ( row_1_reg_213 );

    SC_METHOD(thread_row_6_fu_680_p2);
    sensitive << ( row_3_reg_305 );

    SC_METHOD(thread_row_boundary_fu_433_p2);
    sensitive << ( input_row_read_reg_767 );

    SC_METHOD(thread_row_fu_490_p2);
    sensitive << ( row_2_reg_235 );

    SC_METHOD(thread_sext_ln31_fu_401_p1);
    sensitive << ( add_ln31_fu_396_p2 );

    SC_METHOD(thread_sext_ln60_fu_560_p1);
    sensitive << ( add_ln60_fu_555_p2 );

    SC_METHOD(thread_sext_ln65_1_fu_666_p1);
    sensitive << ( add_ln65_3_fu_661_p2 );

    SC_METHOD(thread_sext_ln65_cast_fu_591_p3);
    sensitive << ( add_ln65_fu_585_p2 );

    SC_METHOD(thread_sext_ln65_fu_652_p1);
    sensitive << ( add_ln65_2_fu_647_p2 );

    SC_METHOD(thread_sext_ln84_fu_755_p1);
    sensitive << ( add_ln84_fu_750_p2 );

    SC_METHOD(thread_stream_input_TDATA_blk_n);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln41_fu_447_p2 );
    sensitive << ( stream_input_TVALID_int );

    SC_METHOD(thread_stream_input_TREADY);
    sensitive << ( stream_input_TVALID );
    sensitive << ( regslice_both_stream_input_V_data_U_ack_in );

    SC_METHOD(thread_stream_input_TREADY_int);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln41_fu_447_p2 );
    sensitive << ( stream_input_TVALID_int );

    SC_METHOD(thread_stream_kernel_TDATA_blk_n);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln29_fu_371_p2 );
    sensitive << ( stream_kernel_TVALID_int );

    SC_METHOD(thread_stream_kernel_TREADY);
    sensitive << ( stream_kernel_TVALID );
    sensitive << ( regslice_both_stream_kernel_V_data_U_ack_in );

    SC_METHOD(thread_stream_kernel_TREADY_int);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln29_fu_371_p2 );
    sensitive << ( stream_kernel_TVALID_int );

    SC_METHOD(thread_stream_output_TDATA_blk_n);
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( stream_output_TREADY_int );

    SC_METHOD(thread_stream_output_TLAST_int);
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( tmp_last_reg_952 );

    SC_METHOD(thread_stream_output_TVALID);
    sensitive << ( regslice_both_stream_output_V_data_U_vld_out );

    SC_METHOD(thread_stream_output_TVALID_int);
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( stream_output_TREADY_int );

    SC_METHOD(thread_sub_ln31_fu_365_p2);
    sensitive << ( zext_ln31_1_fu_361_p1 );
    sensitive << ( zext_ln31_fu_349_p1 );

    SC_METHOD(thread_sub_ln60_fu_520_p2);
    sensitive << ( zext_ln60_cast_fu_500_p3 );
    sensitive << ( zext_ln60_2_cast_fu_512_p3 );

    SC_METHOD(thread_sub_ln65_fu_615_p2);
    sensitive << ( zext_ln65_2_fu_611_p1 );
    sensitive << ( zext_ln65_1_fu_599_p1 );

    SC_METHOD(thread_sub_ln84_fu_715_p2);
    sensitive << ( zext_ln84_cast_fu_695_p3 );
    sensitive << ( zext_ln84_2_cast_fu_707_p3 );

    SC_METHOD(thread_tmp_8_fu_603_p3);
    sensitive << ( m_0_reg_271 );

    SC_METHOD(thread_tmp_fu_353_p3);
    sensitive << ( row_0_reg_191 );

    SC_METHOD(thread_tmp_last_1_fu_388_p1);
    sensitive << ( stream_kernel_TLAST_int );

    SC_METHOD(thread_tmp_last_2_fu_463_p1);
    sensitive << ( stream_input_TLAST_int );

    SC_METHOD(thread_tmp_last_fu_741_p2);
    sensitive << ( icmp_ln79_reg_934 );
    sensitive << ( icmp_ln79_1_fu_736_p2 );

    SC_METHOD(thread_trunc_ln41_fu_421_p1);
    sensitive << ( row_1_reg_213 );

    SC_METHOD(thread_trunc_ln43_fu_467_p1);
    sensitive << ( col_1_reg_224 );

    SC_METHOD(thread_trunc_ln60_1_fu_508_p1);
    sensitive << ( row_2_reg_235 );

    SC_METHOD(thread_trunc_ln60_2_fu_551_p1);
    sensitive << ( col_2_reg_247 );

    SC_METHOD(thread_trunc_ln60_fu_496_p1);
    sensitive << ( row_2_reg_235 );

    SC_METHOD(thread_trunc_ln65_1_fu_637_p1);
    sensitive << ( col_2_reg_247 );

    SC_METHOD(thread_trunc_ln65_fu_581_p1);
    sensitive << ( row_2_reg_235 );

    SC_METHOD(thread_trunc_ln84_1_fu_703_p1);
    sensitive << ( row_3_reg_305 );

    SC_METHOD(thread_trunc_ln84_2_fu_746_p1);
    sensitive << ( col_3_reg_316 );

    SC_METHOD(thread_trunc_ln84_fu_691_p1);
    sensitive << ( row_3_reg_305 );

    SC_METHOD(thread_zext_ln31_1_fu_361_p1);
    sensitive << ( tmp_fu_353_p3 );

    SC_METHOD(thread_zext_ln31_2_fu_392_p1);
    sensitive << ( col_0_reg_202 );

    SC_METHOD(thread_zext_ln31_fu_349_p1);
    sensitive << ( row_0_reg_191 );

    SC_METHOD(thread_zext_ln40_fu_406_p1);
    sensitive << ( row_1_reg_213 );

    SC_METHOD(thread_zext_ln41_fu_443_p1);
    sensitive << ( col_1_reg_224 );

    SC_METHOD(thread_zext_ln43_cast_fu_425_p3);
    sensitive << ( trunc_ln41_fu_421_p1 );

    SC_METHOD(thread_zext_ln43_fu_476_p1);
    sensitive << ( add_ln43_fu_471_p2 );

    SC_METHOD(thread_zext_ln57_fu_481_p1);
    sensitive << ( row_2_reg_235 );

    SC_METHOD(thread_zext_ln58_fu_536_p1);
    sensitive << ( col_2_reg_247 );

    SC_METHOD(thread_zext_ln60_2_cast_fu_512_p3);
    sensitive << ( trunc_ln60_1_fu_508_p1 );

    SC_METHOD(thread_zext_ln60_cast_fu_500_p3);
    sensitive << ( trunc_ln60_fu_496_p1 );

    SC_METHOD(thread_zext_ln65_1_fu_599_p1);
    sensitive << ( m_0_reg_271 );

    SC_METHOD(thread_zext_ln65_2_fu_611_p1);
    sensitive << ( tmp_8_fu_603_p3 );

    SC_METHOD(thread_zext_ln65_3_fu_633_p1);
    sensitive << ( n_0_reg_294 );

    SC_METHOD(thread_zext_ln65_4_fu_657_p1);
    sensitive << ( n_0_reg_294 );

    SC_METHOD(thread_zext_ln65_fu_577_p1);
    sensitive << ( m_0_reg_271 );

    SC_METHOD(thread_zext_ln76_fu_671_p1);
    sensitive << ( row_3_reg_305 );

    SC_METHOD(thread_zext_ln77_fu_721_p1);
    sensitive << ( col_3_reg_316 );

    SC_METHOD(thread_zext_ln84_2_cast_fu_707_p3);
    sensitive << ( trunc_ln84_1_fu_703_p1 );

    SC_METHOD(thread_zext_ln84_cast_fu_695_p3);
    sensitive << ( trunc_ln84_fu_691_p1 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln29_fu_371_p2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln41_fu_447_p2 );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln28_fu_337_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln40_fu_410_p2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( icmp_ln57_fu_485_p2 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( icmp_ln58_fu_540_p2 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( icmp_ln63_fu_565_p2 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( icmp_ln64_fu_621_p2 );
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( regslice_both_stream_output_V_data_U_apdone_blk );
    sensitive << ( icmp_ln76_fu_675_p2 );
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( icmp_ln77_fu_725_p2 );
    sensitive << ( tmp_last_1_fu_388_p1 );
    sensitive << ( tmp_last_2_fu_463_p1 );
    sensitive << ( stream_kernel_TVALID_int );
    sensitive << ( stream_input_TVALID_int );
    sensitive << ( stream_output_TREADY_int );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "00000000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "conv2d_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, stream_kernel_TDATA, "(port)stream_kernel_TDATA");
    sc_trace(mVcdFile, stream_kernel_TVALID, "(port)stream_kernel_TVALID");
    sc_trace(mVcdFile, stream_kernel_TREADY, "(port)stream_kernel_TREADY");
    sc_trace(mVcdFile, stream_kernel_TLAST, "(port)stream_kernel_TLAST");
    sc_trace(mVcdFile, stream_input_TDATA, "(port)stream_input_TDATA");
    sc_trace(mVcdFile, stream_input_TVALID, "(port)stream_input_TVALID");
    sc_trace(mVcdFile, stream_input_TREADY, "(port)stream_input_TREADY");
    sc_trace(mVcdFile, stream_input_TLAST, "(port)stream_input_TLAST");
    sc_trace(mVcdFile, stream_output_TDATA, "(port)stream_output_TDATA");
    sc_trace(mVcdFile, stream_output_TVALID, "(port)stream_output_TVALID");
    sc_trace(mVcdFile, stream_output_TREADY, "(port)stream_output_TREADY");
    sc_trace(mVcdFile, stream_output_TLAST, "(port)stream_output_TLAST");
    sc_trace(mVcdFile, s_axi_AXILiteS_AWVALID, "(port)s_axi_AXILiteS_AWVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_AWREADY, "(port)s_axi_AXILiteS_AWREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_AWADDR, "(port)s_axi_AXILiteS_AWADDR");
    sc_trace(mVcdFile, s_axi_AXILiteS_WVALID, "(port)s_axi_AXILiteS_WVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_WREADY, "(port)s_axi_AXILiteS_WREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_WDATA, "(port)s_axi_AXILiteS_WDATA");
    sc_trace(mVcdFile, s_axi_AXILiteS_WSTRB, "(port)s_axi_AXILiteS_WSTRB");
    sc_trace(mVcdFile, s_axi_AXILiteS_ARVALID, "(port)s_axi_AXILiteS_ARVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_ARREADY, "(port)s_axi_AXILiteS_ARREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_ARADDR, "(port)s_axi_AXILiteS_ARADDR");
    sc_trace(mVcdFile, s_axi_AXILiteS_RVALID, "(port)s_axi_AXILiteS_RVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_RREADY, "(port)s_axi_AXILiteS_RREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_RDATA, "(port)s_axi_AXILiteS_RDATA");
    sc_trace(mVcdFile, s_axi_AXILiteS_RRESP, "(port)s_axi_AXILiteS_RRESP");
    sc_trace(mVcdFile, s_axi_AXILiteS_BVALID, "(port)s_axi_AXILiteS_BVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_BREADY, "(port)s_axi_AXILiteS_BREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_BRESP, "(port)s_axi_AXILiteS_BRESP");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, input_row, "input_row");
    sc_trace(mVcdFile, input_col, "input_col");
    sc_trace(mVcdFile, stream_kernel_TDATA_blk_n, "stream_kernel_TDATA_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, icmp_ln29_fu_371_p2, "icmp_ln29_fu_371_p2");
    sc_trace(mVcdFile, stream_input_TDATA_blk_n, "stream_input_TDATA_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, icmp_ln41_fu_447_p2, "icmp_ln41_fu_447_p2");
    sc_trace(mVcdFile, stream_output_TDATA_blk_n, "stream_output_TDATA_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state19, "ap_CS_fsm_state19");
    sc_trace(mVcdFile, ap_CS_fsm_state20, "ap_CS_fsm_state20");
    sc_trace(mVcdFile, input_col_read_reg_760, "input_col_read_reg_760");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, input_row_read_reg_767, "input_row_read_reg_767");
    sc_trace(mVcdFile, row_4_fu_343_p2, "row_4_fu_343_p2");
    sc_trace(mVcdFile, row_4_reg_777, "row_4_reg_777");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, sub_ln31_fu_365_p2, "sub_ln31_fu_365_p2");
    sc_trace(mVcdFile, sub_ln31_reg_782, "sub_ln31_reg_782");
    sc_trace(mVcdFile, icmp_ln28_fu_337_p2, "icmp_ln28_fu_337_p2");
    sc_trace(mVcdFile, col_fu_377_p2, "col_fu_377_p2");
    sc_trace(mVcdFile, ap_block_state3, "ap_block_state3");
    sc_trace(mVcdFile, row_5_fu_415_p2, "row_5_fu_415_p2");
    sc_trace(mVcdFile, row_5_reg_801, "row_5_reg_801");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, zext_ln43_cast_fu_425_p3, "zext_ln43_cast_fu_425_p3");
    sc_trace(mVcdFile, zext_ln43_cast_reg_806, "zext_ln43_cast_reg_806");
    sc_trace(mVcdFile, icmp_ln40_fu_410_p2, "icmp_ln40_fu_410_p2");
    sc_trace(mVcdFile, row_boundary_fu_433_p2, "row_boundary_fu_433_p2");
    sc_trace(mVcdFile, row_boundary_reg_811, "row_boundary_reg_811");
    sc_trace(mVcdFile, col_boundary_fu_438_p2, "col_boundary_fu_438_p2");
    sc_trace(mVcdFile, col_boundary_reg_817, "col_boundary_reg_817");
    sc_trace(mVcdFile, col_4_fu_452_p2, "col_4_fu_452_p2");
    sc_trace(mVcdFile, ap_block_state5, "ap_block_state5");
    sc_trace(mVcdFile, row_fu_490_p2, "row_fu_490_p2");
    sc_trace(mVcdFile, row_reg_837, "row_reg_837");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, sub_ln60_fu_520_p2, "sub_ln60_fu_520_p2");
    sc_trace(mVcdFile, sub_ln60_reg_842, "sub_ln60_reg_842");
    sc_trace(mVcdFile, icmp_ln57_fu_485_p2, "icmp_ln57_fu_485_p2");
    sc_trace(mVcdFile, add_ln79_fu_526_p2, "add_ln79_fu_526_p2");
    sc_trace(mVcdFile, add_ln79_reg_847, "add_ln79_reg_847");
    sc_trace(mVcdFile, add_ln79_1_fu_531_p2, "add_ln79_1_fu_531_p2");
    sc_trace(mVcdFile, add_ln79_1_reg_852, "add_ln79_1_reg_852");
    sc_trace(mVcdFile, col_5_fu_545_p2, "col_5_fu_545_p2");
    sc_trace(mVcdFile, col_5_reg_860, "col_5_reg_860");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, output_addr_reg_865, "output_addr_reg_865");
    sc_trace(mVcdFile, icmp_ln58_fu_540_p2, "icmp_ln58_fu_540_p2");
    sc_trace(mVcdFile, m_fu_571_p2, "m_fu_571_p2");
    sc_trace(mVcdFile, m_reg_873, "m_reg_873");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, sext_ln65_cast_fu_591_p3, "sext_ln65_cast_fu_591_p3");
    sc_trace(mVcdFile, sext_ln65_cast_reg_878, "sext_ln65_cast_reg_878");
    sc_trace(mVcdFile, icmp_ln63_fu_565_p2, "icmp_ln63_fu_565_p2");
    sc_trace(mVcdFile, sub_ln65_fu_615_p2, "sub_ln65_fu_615_p2");
    sc_trace(mVcdFile, sub_ln65_reg_883, "sub_ln65_reg_883");
    sc_trace(mVcdFile, n_fu_627_p2, "n_fu_627_p2");
    sc_trace(mVcdFile, n_reg_891, "n_reg_891");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, icmp_ln64_fu_621_p2, "icmp_ln64_fu_621_p2");
    sc_trace(mVcdFile, input_q0, "input_q0");
    sc_trace(mVcdFile, input_load_reg_906, "input_load_reg_906");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, kernel_q0, "kernel_q0");
    sc_trace(mVcdFile, kernel_load_reg_911, "kernel_load_reg_911");
    sc_trace(mVcdFile, grp_fu_333_p2, "grp_fu_333_p2");
    sc_trace(mVcdFile, x_reg_916, "x_reg_916");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, grp_fu_327_p2, "grp_fu_327_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state16, "ap_CS_fsm_state16");
    sc_trace(mVcdFile, row_6_fu_680_p2, "row_6_fu_680_p2");
    sc_trace(mVcdFile, row_6_reg_929, "row_6_reg_929");
    sc_trace(mVcdFile, ap_CS_fsm_state17, "ap_CS_fsm_state17");
    sc_trace(mVcdFile, regslice_both_stream_output_V_data_U_apdone_blk, "regslice_both_stream_output_V_data_U_apdone_blk");
    sc_trace(mVcdFile, icmp_ln79_fu_686_p2, "icmp_ln79_fu_686_p2");
    sc_trace(mVcdFile, icmp_ln79_reg_934, "icmp_ln79_reg_934");
    sc_trace(mVcdFile, icmp_ln76_fu_675_p2, "icmp_ln76_fu_675_p2");
    sc_trace(mVcdFile, sub_ln84_fu_715_p2, "sub_ln84_fu_715_p2");
    sc_trace(mVcdFile, sub_ln84_reg_939, "sub_ln84_reg_939");
    sc_trace(mVcdFile, col_6_fu_730_p2, "col_6_fu_730_p2");
    sc_trace(mVcdFile, col_6_reg_947, "col_6_reg_947");
    sc_trace(mVcdFile, ap_CS_fsm_state18, "ap_CS_fsm_state18");
    sc_trace(mVcdFile, tmp_last_fu_741_p2, "tmp_last_fu_741_p2");
    sc_trace(mVcdFile, tmp_last_reg_952, "tmp_last_reg_952");
    sc_trace(mVcdFile, icmp_ln77_fu_725_p2, "icmp_ln77_fu_725_p2");
    sc_trace(mVcdFile, output_q0, "output_q0");
    sc_trace(mVcdFile, input_address0, "input_address0");
    sc_trace(mVcdFile, input_ce0, "input_ce0");
    sc_trace(mVcdFile, input_we0, "input_we0");
    sc_trace(mVcdFile, kernel_address0, "kernel_address0");
    sc_trace(mVcdFile, kernel_ce0, "kernel_ce0");
    sc_trace(mVcdFile, kernel_we0, "kernel_we0");
    sc_trace(mVcdFile, output_address0, "output_address0");
    sc_trace(mVcdFile, output_ce0, "output_ce0");
    sc_trace(mVcdFile, output_we0, "output_we0");
    sc_trace(mVcdFile, output_d0, "output_d0");
    sc_trace(mVcdFile, row_0_reg_191, "row_0_reg_191");
    sc_trace(mVcdFile, tmp_last_1_fu_388_p1, "tmp_last_1_fu_388_p1");
    sc_trace(mVcdFile, col_0_reg_202, "col_0_reg_202");
    sc_trace(mVcdFile, row_1_reg_213, "row_1_reg_213");
    sc_trace(mVcdFile, tmp_last_2_fu_463_p1, "tmp_last_2_fu_463_p1");
    sc_trace(mVcdFile, col_1_reg_224, "col_1_reg_224");
    sc_trace(mVcdFile, row_2_reg_235, "row_2_reg_235");
    sc_trace(mVcdFile, col_2_reg_247, "col_2_reg_247");
    sc_trace(mVcdFile, empty_6_reg_259, "empty_6_reg_259");
    sc_trace(mVcdFile, m_0_reg_271, "m_0_reg_271");
    sc_trace(mVcdFile, empty_8_reg_282, "empty_8_reg_282");
    sc_trace(mVcdFile, n_0_reg_294, "n_0_reg_294");
    sc_trace(mVcdFile, row_3_reg_305, "row_3_reg_305");
    sc_trace(mVcdFile, col_3_reg_316, "col_3_reg_316");
    sc_trace(mVcdFile, sext_ln31_fu_401_p1, "sext_ln31_fu_401_p1");
    sc_trace(mVcdFile, zext_ln43_fu_476_p1, "zext_ln43_fu_476_p1");
    sc_trace(mVcdFile, sext_ln60_fu_560_p1, "sext_ln60_fu_560_p1");
    sc_trace(mVcdFile, sext_ln65_fu_652_p1, "sext_ln65_fu_652_p1");
    sc_trace(mVcdFile, sext_ln65_1_fu_666_p1, "sext_ln65_1_fu_666_p1");
    sc_trace(mVcdFile, sext_ln84_fu_755_p1, "sext_ln84_fu_755_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, tmp_fu_353_p3, "tmp_fu_353_p3");
    sc_trace(mVcdFile, zext_ln31_1_fu_361_p1, "zext_ln31_1_fu_361_p1");
    sc_trace(mVcdFile, zext_ln31_fu_349_p1, "zext_ln31_fu_349_p1");
    sc_trace(mVcdFile, zext_ln31_2_fu_392_p1, "zext_ln31_2_fu_392_p1");
    sc_trace(mVcdFile, add_ln31_fu_396_p2, "add_ln31_fu_396_p2");
    sc_trace(mVcdFile, zext_ln40_fu_406_p1, "zext_ln40_fu_406_p1");
    sc_trace(mVcdFile, trunc_ln41_fu_421_p1, "trunc_ln41_fu_421_p1");
    sc_trace(mVcdFile, zext_ln41_fu_443_p1, "zext_ln41_fu_443_p1");
    sc_trace(mVcdFile, trunc_ln43_fu_467_p1, "trunc_ln43_fu_467_p1");
    sc_trace(mVcdFile, add_ln43_fu_471_p2, "add_ln43_fu_471_p2");
    sc_trace(mVcdFile, zext_ln57_fu_481_p1, "zext_ln57_fu_481_p1");
    sc_trace(mVcdFile, trunc_ln60_fu_496_p1, "trunc_ln60_fu_496_p1");
    sc_trace(mVcdFile, trunc_ln60_1_fu_508_p1, "trunc_ln60_1_fu_508_p1");
    sc_trace(mVcdFile, zext_ln60_cast_fu_500_p3, "zext_ln60_cast_fu_500_p3");
    sc_trace(mVcdFile, zext_ln60_2_cast_fu_512_p3, "zext_ln60_2_cast_fu_512_p3");
    sc_trace(mVcdFile, zext_ln58_fu_536_p1, "zext_ln58_fu_536_p1");
    sc_trace(mVcdFile, trunc_ln60_2_fu_551_p1, "trunc_ln60_2_fu_551_p1");
    sc_trace(mVcdFile, add_ln60_fu_555_p2, "add_ln60_fu_555_p2");
    sc_trace(mVcdFile, trunc_ln65_fu_581_p1, "trunc_ln65_fu_581_p1");
    sc_trace(mVcdFile, zext_ln65_fu_577_p1, "zext_ln65_fu_577_p1");
    sc_trace(mVcdFile, add_ln65_fu_585_p2, "add_ln65_fu_585_p2");
    sc_trace(mVcdFile, tmp_8_fu_603_p3, "tmp_8_fu_603_p3");
    sc_trace(mVcdFile, zext_ln65_2_fu_611_p1, "zext_ln65_2_fu_611_p1");
    sc_trace(mVcdFile, zext_ln65_1_fu_599_p1, "zext_ln65_1_fu_599_p1");
    sc_trace(mVcdFile, trunc_ln65_1_fu_637_p1, "trunc_ln65_1_fu_637_p1");
    sc_trace(mVcdFile, zext_ln65_3_fu_633_p1, "zext_ln65_3_fu_633_p1");
    sc_trace(mVcdFile, add_ln65_1_fu_641_p2, "add_ln65_1_fu_641_p2");
    sc_trace(mVcdFile, add_ln65_2_fu_647_p2, "add_ln65_2_fu_647_p2");
    sc_trace(mVcdFile, zext_ln65_4_fu_657_p1, "zext_ln65_4_fu_657_p1");
    sc_trace(mVcdFile, add_ln65_3_fu_661_p2, "add_ln65_3_fu_661_p2");
    sc_trace(mVcdFile, zext_ln76_fu_671_p1, "zext_ln76_fu_671_p1");
    sc_trace(mVcdFile, trunc_ln84_fu_691_p1, "trunc_ln84_fu_691_p1");
    sc_trace(mVcdFile, trunc_ln84_1_fu_703_p1, "trunc_ln84_1_fu_703_p1");
    sc_trace(mVcdFile, zext_ln84_cast_fu_695_p3, "zext_ln84_cast_fu_695_p3");
    sc_trace(mVcdFile, zext_ln84_2_cast_fu_707_p3, "zext_ln84_2_cast_fu_707_p3");
    sc_trace(mVcdFile, zext_ln77_fu_721_p1, "zext_ln77_fu_721_p1");
    sc_trace(mVcdFile, icmp_ln79_1_fu_736_p2, "icmp_ln79_1_fu_736_p2");
    sc_trace(mVcdFile, trunc_ln84_2_fu_746_p1, "trunc_ln84_2_fu_746_p1");
    sc_trace(mVcdFile, add_ln84_fu_750_p2, "add_ln84_fu_750_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, regslice_both_stream_kernel_V_data_U_apdone_blk, "regslice_both_stream_kernel_V_data_U_apdone_blk");
    sc_trace(mVcdFile, stream_kernel_TDATA_int, "stream_kernel_TDATA_int");
    sc_trace(mVcdFile, stream_kernel_TVALID_int, "stream_kernel_TVALID_int");
    sc_trace(mVcdFile, stream_kernel_TREADY_int, "stream_kernel_TREADY_int");
    sc_trace(mVcdFile, regslice_both_stream_kernel_V_data_U_ack_in, "regslice_both_stream_kernel_V_data_U_ack_in");
    sc_trace(mVcdFile, regslice_both_w1_stream_kernel_V_last_U_apdone_blk, "regslice_both_w1_stream_kernel_V_last_U_apdone_blk");
    sc_trace(mVcdFile, stream_kernel_TLAST_int, "stream_kernel_TLAST_int");
    sc_trace(mVcdFile, regslice_both_w1_stream_kernel_V_last_U_vld_out, "regslice_both_w1_stream_kernel_V_last_U_vld_out");
    sc_trace(mVcdFile, regslice_both_w1_stream_kernel_V_last_U_ack_in, "regslice_both_w1_stream_kernel_V_last_U_ack_in");
    sc_trace(mVcdFile, regslice_both_stream_input_V_data_U_apdone_blk, "regslice_both_stream_input_V_data_U_apdone_blk");
    sc_trace(mVcdFile, stream_input_TDATA_int, "stream_input_TDATA_int");
    sc_trace(mVcdFile, stream_input_TVALID_int, "stream_input_TVALID_int");
    sc_trace(mVcdFile, stream_input_TREADY_int, "stream_input_TREADY_int");
    sc_trace(mVcdFile, regslice_both_stream_input_V_data_U_ack_in, "regslice_both_stream_input_V_data_U_ack_in");
    sc_trace(mVcdFile, regslice_both_w1_stream_input_V_last_U_apdone_blk, "regslice_both_w1_stream_input_V_last_U_apdone_blk");
    sc_trace(mVcdFile, stream_input_TLAST_int, "stream_input_TLAST_int");
    sc_trace(mVcdFile, regslice_both_w1_stream_input_V_last_U_vld_out, "regslice_both_w1_stream_input_V_last_U_vld_out");
    sc_trace(mVcdFile, regslice_both_w1_stream_input_V_last_U_ack_in, "regslice_both_w1_stream_input_V_last_U_ack_in");
    sc_trace(mVcdFile, stream_output_TVALID_int, "stream_output_TVALID_int");
    sc_trace(mVcdFile, stream_output_TREADY_int, "stream_output_TREADY_int");
    sc_trace(mVcdFile, regslice_both_stream_output_V_data_U_vld_out, "regslice_both_stream_output_V_data_U_vld_out");
    sc_trace(mVcdFile, regslice_both_w1_stream_output_V_last_U_apdone_blk, "regslice_both_w1_stream_output_V_last_U_apdone_blk");
    sc_trace(mVcdFile, stream_output_TLAST_int, "stream_output_TLAST_int");
    sc_trace(mVcdFile, regslice_both_w1_stream_output_V_last_U_ack_in_dummy, "regslice_both_w1_stream_output_V_last_U_ack_in_dummy");
    sc_trace(mVcdFile, regslice_both_w1_stream_output_V_last_U_vld_out, "regslice_both_w1_stream_output_V_last_U_vld_out");
#endif

    }
    mHdltvinHandle.open("conv2d.hdltvin.dat");
    mHdltvoutHandle.open("conv2d.hdltvout.dat");
}

conv2d::~conv2d() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete conv2d_AXILiteS_s_axi_U;
    delete input_U;
    delete kernel_U;
    delete output_U;
    delete conv2d_fadd_32ns_bkb_U1;
    delete conv2d_fmul_32ns_cud_U2;
    delete regslice_both_stream_kernel_V_data_U;
    delete regslice_both_w1_stream_kernel_V_last_U;
    delete regslice_both_stream_input_V_data_U;
    delete regslice_both_w1_stream_input_V_last_U;
    delete regslice_both_stream_output_V_data_U;
    delete regslice_both_w1_stream_output_V_last_U;
}

void conv2d::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void conv2d::thread_ap_clk_no_reset_() {
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln29_fu_371_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_last_1_fu_388_p1.read()) && 
         !(esl_seteq<1,1,1>(icmp_ln29_fu_371_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, stream_kernel_TVALID_int.read())))) {
        col_0_reg_202 = col_fu_377_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln28_fu_337_p2.read()))) {
        col_0_reg_202 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(icmp_ln41_fu_447_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_last_2_fu_463_p1.read()) && 
         !(esl_seteq<1,1,1>(icmp_ln41_fu_447_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_0, stream_input_TVALID_int.read())))) {
        col_1_reg_224 = col_4_fu_452_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln40_fu_410_p2.read()))) {
        col_1_reg_224 = ap_const_lv31_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln63_fu_565_p2.read()))) {
        col_2_reg_247 = col_5_reg_860.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln57_fu_485_p2.read()))) {
        col_2_reg_247 = ap_const_lv31_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()) && 
         esl_seteq<1,1,1>(regslice_both_stream_output_V_data_U_apdone_blk.read(), ap_const_logic_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln76_fu_675_p2.read()))) {
        col_3_reg_316 = ap_const_lv31_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read()) && 
                esl_seteq<1,1,1>(stream_output_TREADY_int.read(), ap_const_logic_1))) {
        col_3_reg_316 = col_6_reg_947.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln64_fu_621_p2.read()))) {
        empty_6_reg_259 = empty_8_reg_282.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln58_fu_540_p2.read()))) {
        empty_6_reg_259 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln63_fu_565_p2.read()))) {
        empty_8_reg_282 = empty_6_reg_259.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        empty_8_reg_282 = grp_fu_327_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln64_fu_621_p2.read()))) {
        m_0_reg_271 = m_reg_873.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln58_fu_540_p2.read()))) {
        m_0_reg_271 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln63_fu_565_p2.read()))) {
        n_0_reg_294 = ap_const_lv2_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        n_0_reg_294 = n_reg_891.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         (esl_seteq<1,1,1>(ap_const_lv1_1, tmp_last_1_fu_388_p1.read()) || 
          esl_seteq<1,1,1>(icmp_ln29_fu_371_p2.read(), ap_const_lv1_1)) && 
         !(esl_seteq<1,1,1>(icmp_ln29_fu_371_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, stream_kernel_TVALID_int.read())))) {
        row_0_reg_191 = row_4_reg_777.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        row_0_reg_191 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln28_fu_337_p2.read()))) {
        row_1_reg_213 = ap_const_lv31_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                (esl_seteq<1,1,1>(ap_const_lv1_1, tmp_last_2_fu_463_p1.read()) || 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln41_fu_447_p2.read())) && 
                !(esl_seteq<1,1,1>(icmp_ln41_fu_447_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_0, stream_input_TVALID_int.read())))) {
        row_1_reg_213 = row_5_reg_801.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln58_fu_540_p2.read()))) {
        row_2_reg_235 = row_reg_837.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln40_fu_410_p2.read()))) {
        row_2_reg_235 = ap_const_lv31_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln77_fu_725_p2.read()))) {
        row_3_reg_305 = row_6_reg_929.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln57_fu_485_p2.read()))) {
        row_3_reg_305 = ap_const_lv31_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln57_fu_485_p2.read()))) {
        add_ln79_1_reg_852 = add_ln79_1_fu_531_p2.read();
        add_ln79_reg_847 = add_ln79_fu_526_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        col_5_reg_860 = col_5_fu_545_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        col_6_reg_947 = col_6_fu_730_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln40_fu_410_p2.read()))) {
        col_boundary_reg_817 = col_boundary_fu_438_p2.read();
        row_boundary_reg_811 = row_boundary_fu_433_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()) && esl_seteq<1,1,1>(regslice_both_stream_output_V_data_U_apdone_blk.read(), ap_const_logic_0) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln76_fu_675_p2.read()))) {
        icmp_ln79_reg_934 = icmp_ln79_fu_686_p2.read();
        sub_ln84_reg_939 = sub_ln84_fu_715_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        input_col_read_reg_760 = input_col.read();
        input_row_read_reg_767 = input_row.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        input_load_reg_906 = input_q0.read();
        kernel_load_reg_911 = kernel_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        m_reg_873 = m_fu_571_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        n_reg_891 = n_fu_627_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln58_fu_540_p2.read()))) {
        output_addr_reg_865 =  (sc_lv<12>) (sext_ln60_fu_560_p1.read());
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        row_4_reg_777 = row_4_fu_343_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        row_5_reg_801 = row_5_fu_415_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()) && esl_seteq<1,1,1>(regslice_both_stream_output_V_data_U_apdone_blk.read(), ap_const_logic_0))) {
        row_6_reg_929 = row_6_fu_680_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        row_reg_837 = row_fu_490_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln63_fu_565_p2.read()))) {
        sext_ln65_cast_reg_878 = sext_ln65_cast_fu_591_p3.read();
        sub_ln65_reg_883 = sub_ln65_fu_615_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln28_fu_337_p2.read()))) {
        sub_ln31_reg_782 = sub_ln31_fu_365_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln57_fu_485_p2.read()))) {
        sub_ln60_reg_842 = sub_ln60_fu_520_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln77_fu_725_p2.read()))) {
        tmp_last_reg_952 = tmp_last_fu_741_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        x_reg_916 = grp_fu_333_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln40_fu_410_p2.read()))) {
        zext_ln43_cast_reg_806 = zext_ln43_cast_fu_425_p3.read();
    }
}

void conv2d::thread_add_ln31_fu_396_p2() {
    add_ln31_fu_396_p2 = (!sub_ln31_reg_782.read().is_01() || !zext_ln31_2_fu_392_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(sub_ln31_reg_782.read()) + sc_biguint<5>(zext_ln31_2_fu_392_p1.read()));
}

void conv2d::thread_add_ln43_fu_471_p2() {
    add_ln43_fu_471_p2 = (!zext_ln43_cast_reg_806.read().is_01() || !trunc_ln43_fu_467_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(zext_ln43_cast_reg_806.read()) + sc_biguint<14>(trunc_ln43_fu_467_p1.read()));
}

void conv2d::thread_add_ln60_fu_555_p2() {
    add_ln60_fu_555_p2 = (!sub_ln60_reg_842.read().is_01() || !trunc_ln60_2_fu_551_p1.read().is_01())? sc_lv<13>(): (sc_biguint<13>(sub_ln60_reg_842.read()) + sc_biguint<13>(trunc_ln60_2_fu_551_p1.read()));
}

void conv2d::thread_add_ln65_1_fu_641_p2() {
    add_ln65_1_fu_641_p2 = (!trunc_ln65_1_fu_637_p1.read().is_01() || !zext_ln65_3_fu_633_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(trunc_ln65_1_fu_637_p1.read()) + sc_biguint<14>(zext_ln65_3_fu_633_p1.read()));
}

void conv2d::thread_add_ln65_2_fu_647_p2() {
    add_ln65_2_fu_647_p2 = (!add_ln65_1_fu_641_p2.read().is_01() || !sext_ln65_cast_reg_878.read().is_01())? sc_lv<14>(): (sc_biguint<14>(add_ln65_1_fu_641_p2.read()) + sc_biguint<14>(sext_ln65_cast_reg_878.read()));
}

void conv2d::thread_add_ln65_3_fu_661_p2() {
    add_ln65_3_fu_661_p2 = (!zext_ln65_4_fu_657_p1.read().is_01() || !sub_ln65_reg_883.read().is_01())? sc_lv<5>(): (sc_biguint<5>(zext_ln65_4_fu_657_p1.read()) + sc_biguint<5>(sub_ln65_reg_883.read()));
}

void conv2d::thread_add_ln65_fu_585_p2() {
    add_ln65_fu_585_p2 = (!trunc_ln65_fu_581_p1.read().is_01() || !zext_ln65_fu_577_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(trunc_ln65_fu_581_p1.read()) + sc_biguint<8>(zext_ln65_fu_577_p1.read()));
}

void conv2d::thread_add_ln79_1_fu_531_p2() {
    add_ln79_1_fu_531_p2 = (!input_col_read_reg_760.read().is_01() || !ap_const_lv32_FFFFFFFD.is_01())? sc_lv<32>(): (sc_biguint<32>(input_col_read_reg_760.read()) + sc_bigint<32>(ap_const_lv32_FFFFFFFD));
}

void conv2d::thread_add_ln79_fu_526_p2() {
    add_ln79_fu_526_p2 = (!input_row_read_reg_767.read().is_01() || !ap_const_lv32_FFFFFFFD.is_01())? sc_lv<32>(): (sc_biguint<32>(input_row_read_reg_767.read()) + sc_bigint<32>(ap_const_lv32_FFFFFFFD));
}

void conv2d::thread_add_ln84_fu_750_p2() {
    add_ln84_fu_750_p2 = (!sub_ln84_reg_939.read().is_01() || !trunc_ln84_2_fu_746_p1.read().is_01())? sc_lv<13>(): (sc_biguint<13>(sub_ln84_reg_939.read()) + sc_biguint<13>(trunc_ln84_2_fu_746_p1.read()));
}

void conv2d::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void conv2d::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void conv2d::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void conv2d::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void conv2d::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void conv2d::thread_ap_CS_fsm_state16() {
    ap_CS_fsm_state16 = ap_CS_fsm.read()[15];
}

void conv2d::thread_ap_CS_fsm_state17() {
    ap_CS_fsm_state17 = ap_CS_fsm.read()[16];
}

void conv2d::thread_ap_CS_fsm_state18() {
    ap_CS_fsm_state18 = ap_CS_fsm.read()[17];
}

void conv2d::thread_ap_CS_fsm_state19() {
    ap_CS_fsm_state19 = ap_CS_fsm.read()[18];
}

void conv2d::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void conv2d::thread_ap_CS_fsm_state20() {
    ap_CS_fsm_state20 = ap_CS_fsm.read()[19];
}

void conv2d::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void conv2d::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void conv2d::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void conv2d::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void conv2d::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void conv2d::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void conv2d::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void conv2d::thread_ap_block_state3() {
    ap_block_state3 = (esl_seteq<1,1,1>(icmp_ln29_fu_371_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, stream_kernel_TVALID_int.read()));
}

void conv2d::thread_ap_block_state5() {
    ap_block_state5 = (esl_seteq<1,1,1>(icmp_ln41_fu_447_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_0, stream_input_TVALID_int.read()));
}

void conv2d::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void conv2d::thread_col_4_fu_452_p2() {
    col_4_fu_452_p2 = (!col_1_reg_224.read().is_01() || !ap_const_lv31_1.is_01())? sc_lv<31>(): (sc_biguint<31>(col_1_reg_224.read()) + sc_biguint<31>(ap_const_lv31_1));
}

void conv2d::thread_col_5_fu_545_p2() {
    col_5_fu_545_p2 = (!col_2_reg_247.read().is_01() || !ap_const_lv31_1.is_01())? sc_lv<31>(): (sc_biguint<31>(col_2_reg_247.read()) + sc_biguint<31>(ap_const_lv31_1));
}

void conv2d::thread_col_6_fu_730_p2() {
    col_6_fu_730_p2 = (!col_3_reg_316.read().is_01() || !ap_const_lv31_1.is_01())? sc_lv<31>(): (sc_biguint<31>(col_3_reg_316.read()) + sc_biguint<31>(ap_const_lv31_1));
}

void conv2d::thread_col_boundary_fu_438_p2() {
    col_boundary_fu_438_p2 = (!input_col_read_reg_760.read().is_01() || !ap_const_lv32_FFFFFFFE.is_01())? sc_lv<32>(): (sc_biguint<32>(input_col_read_reg_760.read()) + sc_bigint<32>(ap_const_lv32_FFFFFFFE));
}

void conv2d::thread_col_fu_377_p2() {
    col_fu_377_p2 = (!col_0_reg_202.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(col_0_reg_202.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void conv2d::thread_icmp_ln28_fu_337_p2() {
    icmp_ln28_fu_337_p2 = (!row_0_reg_191.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(row_0_reg_191.read() == ap_const_lv2_3);
}

void conv2d::thread_icmp_ln29_fu_371_p2() {
    icmp_ln29_fu_371_p2 = (!col_0_reg_202.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(col_0_reg_202.read() == ap_const_lv2_3);
}

void conv2d::thread_icmp_ln40_fu_410_p2() {
    icmp_ln40_fu_410_p2 = (!zext_ln40_fu_406_p1.read().is_01() || !input_row_read_reg_767.read().is_01())? sc_lv<1>(): (sc_bigint<32>(zext_ln40_fu_406_p1.read()) < sc_bigint<32>(input_row_read_reg_767.read()));
}

void conv2d::thread_icmp_ln41_fu_447_p2() {
    icmp_ln41_fu_447_p2 = (!zext_ln41_fu_443_p1.read().is_01() || !input_col_read_reg_760.read().is_01())? sc_lv<1>(): (sc_bigint<32>(zext_ln41_fu_443_p1.read()) < sc_bigint<32>(input_col_read_reg_760.read()));
}

void conv2d::thread_icmp_ln57_fu_485_p2() {
    icmp_ln57_fu_485_p2 = (!zext_ln57_fu_481_p1.read().is_01() || !row_boundary_reg_811.read().is_01())? sc_lv<1>(): (sc_bigint<32>(zext_ln57_fu_481_p1.read()) < sc_bigint<32>(row_boundary_reg_811.read()));
}

void conv2d::thread_icmp_ln58_fu_540_p2() {
    icmp_ln58_fu_540_p2 = (!zext_ln58_fu_536_p1.read().is_01() || !col_boundary_reg_817.read().is_01())? sc_lv<1>(): (sc_bigint<32>(zext_ln58_fu_536_p1.read()) < sc_bigint<32>(col_boundary_reg_817.read()));
}

void conv2d::thread_icmp_ln63_fu_565_p2() {
    icmp_ln63_fu_565_p2 = (!m_0_reg_271.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(m_0_reg_271.read() == ap_const_lv2_3);
}

void conv2d::thread_icmp_ln64_fu_621_p2() {
    icmp_ln64_fu_621_p2 = (!n_0_reg_294.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(n_0_reg_294.read() == ap_const_lv2_3);
}

void conv2d::thread_icmp_ln76_fu_675_p2() {
    icmp_ln76_fu_675_p2 = (!zext_ln76_fu_671_p1.read().is_01() || !row_boundary_reg_811.read().is_01())? sc_lv<1>(): (sc_bigint<32>(zext_ln76_fu_671_p1.read()) < sc_bigint<32>(row_boundary_reg_811.read()));
}

void conv2d::thread_icmp_ln77_fu_725_p2() {
    icmp_ln77_fu_725_p2 = (!zext_ln77_fu_721_p1.read().is_01() || !col_boundary_reg_817.read().is_01())? sc_lv<1>(): (sc_bigint<32>(zext_ln77_fu_721_p1.read()) < sc_bigint<32>(col_boundary_reg_817.read()));
}

void conv2d::thread_icmp_ln79_1_fu_736_p2() {
    icmp_ln79_1_fu_736_p2 = (!zext_ln77_fu_721_p1.read().is_01() || !add_ln79_1_reg_852.read().is_01())? sc_lv<1>(): sc_lv<1>(zext_ln77_fu_721_p1.read() == add_ln79_1_reg_852.read());
}

void conv2d::thread_icmp_ln79_fu_686_p2() {
    icmp_ln79_fu_686_p2 = (!zext_ln76_fu_671_p1.read().is_01() || !add_ln79_reg_847.read().is_01())? sc_lv<1>(): sc_lv<1>(zext_ln76_fu_671_p1.read() == add_ln79_reg_847.read());
}

void conv2d::thread_input_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        input_address0 =  (sc_lv<12>) (sext_ln65_fu_652_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        input_address0 =  (sc_lv<12>) (zext_ln43_fu_476_p1.read());
    } else {
        input_address0 = "XXXXXXXXXXXX";
    }
}

void conv2d::thread_input_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
          !(esl_seteq<1,1,1>(icmp_ln41_fu_447_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_0, stream_input_TVALID_int.read()))))) {
        input_ce0 = ap_const_logic_1;
    } else {
        input_ce0 = ap_const_logic_0;
    }
}

void conv2d::thread_input_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(icmp_ln41_fu_447_p2.read(), ap_const_lv1_1) && 
         !(esl_seteq<1,1,1>(icmp_ln41_fu_447_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_0, stream_input_TVALID_int.read())))) {
        input_we0 = ap_const_logic_1;
    } else {
        input_we0 = ap_const_logic_0;
    }
}

void conv2d::thread_kernel_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        kernel_address0 =  (sc_lv<4>) (sext_ln65_1_fu_666_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        kernel_address0 =  (sc_lv<4>) (sext_ln31_fu_401_p1.read());
    } else {
        kernel_address0 =  (sc_lv<4>) ("XXXX");
    }
}

void conv2d::thread_kernel_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
          !(esl_seteq<1,1,1>(icmp_ln29_fu_371_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, stream_kernel_TVALID_int.read()))))) {
        kernel_ce0 = ap_const_logic_1;
    } else {
        kernel_ce0 = ap_const_logic_0;
    }
}

void conv2d::thread_kernel_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln29_fu_371_p2.read(), ap_const_lv1_0) && 
         !(esl_seteq<1,1,1>(icmp_ln29_fu_371_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, stream_kernel_TVALID_int.read())))) {
        kernel_we0 = ap_const_logic_1;
    } else {
        kernel_we0 = ap_const_logic_0;
    }
}

void conv2d::thread_m_fu_571_p2() {
    m_fu_571_p2 = (!m_0_reg_271.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(m_0_reg_271.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void conv2d::thread_n_fu_627_p2() {
    n_fu_627_p2 = (!n_0_reg_294.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(n_0_reg_294.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void conv2d::thread_output_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        output_address0 =  (sc_lv<12>) (sext_ln84_fu_755_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        output_address0 = output_addr_reg_865.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        output_address0 =  (sc_lv<12>) (sext_ln60_fu_560_p1.read());
    } else {
        output_address0 = "XXXXXXXXXXXX";
    }
}

void conv2d::thread_output_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()))) {
        output_ce0 = ap_const_logic_1;
    } else {
        output_ce0 = ap_const_logic_0;
    }
}

void conv2d::thread_output_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        output_d0 = grp_fu_327_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        output_d0 = ap_const_lv32_0;
    } else {
        output_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void conv2d::thread_output_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln58_fu_540_p2.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()))) {
        output_we0 = ap_const_logic_1;
    } else {
        output_we0 = ap_const_logic_0;
    }
}

void conv2d::thread_row_4_fu_343_p2() {
    row_4_fu_343_p2 = (!row_0_reg_191.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(row_0_reg_191.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void conv2d::thread_row_5_fu_415_p2() {
    row_5_fu_415_p2 = (!row_1_reg_213.read().is_01() || !ap_const_lv31_1.is_01())? sc_lv<31>(): (sc_biguint<31>(row_1_reg_213.read()) + sc_biguint<31>(ap_const_lv31_1));
}

void conv2d::thread_row_6_fu_680_p2() {
    row_6_fu_680_p2 = (!row_3_reg_305.read().is_01() || !ap_const_lv31_1.is_01())? sc_lv<31>(): (sc_biguint<31>(row_3_reg_305.read()) + sc_biguint<31>(ap_const_lv31_1));
}

void conv2d::thread_row_boundary_fu_433_p2() {
    row_boundary_fu_433_p2 = (!input_row_read_reg_767.read().is_01() || !ap_const_lv32_FFFFFFFE.is_01())? sc_lv<32>(): (sc_biguint<32>(input_row_read_reg_767.read()) + sc_bigint<32>(ap_const_lv32_FFFFFFFE));
}

void conv2d::thread_row_fu_490_p2() {
    row_fu_490_p2 = (!row_2_reg_235.read().is_01() || !ap_const_lv31_1.is_01())? sc_lv<31>(): (sc_biguint<31>(row_2_reg_235.read()) + sc_biguint<31>(ap_const_lv31_1));
}

void conv2d::thread_sext_ln31_fu_401_p1() {
    sext_ln31_fu_401_p1 = esl_sext<64,5>(add_ln31_fu_396_p2.read());
}

void conv2d::thread_sext_ln60_fu_560_p1() {
    sext_ln60_fu_560_p1 = esl_sext<64,13>(add_ln60_fu_555_p2.read());
}

void conv2d::thread_sext_ln65_1_fu_666_p1() {
    sext_ln65_1_fu_666_p1 = esl_sext<64,5>(add_ln65_3_fu_661_p2.read());
}

void conv2d::thread_sext_ln65_cast_fu_591_p3() {
    sext_ln65_cast_fu_591_p3 = esl_concat<8,6>(add_ln65_fu_585_p2.read(), ap_const_lv6_0);
}

void conv2d::thread_sext_ln65_fu_652_p1() {
    sext_ln65_fu_652_p1 = esl_sext<64,14>(add_ln65_2_fu_647_p2.read());
}

void conv2d::thread_sext_ln84_fu_755_p1() {
    sext_ln84_fu_755_p1 = esl_sext<64,13>(add_ln84_fu_750_p2.read());
}

void conv2d::thread_stream_input_TDATA_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(icmp_ln41_fu_447_p2.read(), ap_const_lv1_1))) {
        stream_input_TDATA_blk_n = stream_input_TVALID_int.read();
    } else {
        stream_input_TDATA_blk_n = ap_const_logic_1;
    }
}

void conv2d::thread_stream_input_TREADY() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, stream_input_TVALID.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, regslice_both_stream_input_V_data_U_ack_in.read()))) {
        stream_input_TREADY = ap_const_logic_1;
    } else {
        stream_input_TREADY = ap_const_logic_0;
    }
}

void conv2d::thread_stream_input_TREADY_int() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(icmp_ln41_fu_447_p2.read(), ap_const_lv1_1) && 
         !(esl_seteq<1,1,1>(icmp_ln41_fu_447_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_0, stream_input_TVALID_int.read())))) {
        stream_input_TREADY_int = ap_const_logic_1;
    } else {
        stream_input_TREADY_int = ap_const_logic_0;
    }
}

void conv2d::thread_stream_kernel_TDATA_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln29_fu_371_p2.read(), ap_const_lv1_0))) {
        stream_kernel_TDATA_blk_n = stream_kernel_TVALID_int.read();
    } else {
        stream_kernel_TDATA_blk_n = ap_const_logic_1;
    }
}

void conv2d::thread_stream_kernel_TREADY() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, stream_kernel_TVALID.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, regslice_both_stream_kernel_V_data_U_ack_in.read()))) {
        stream_kernel_TREADY = ap_const_logic_1;
    } else {
        stream_kernel_TREADY = ap_const_logic_0;
    }
}

void conv2d::thread_stream_kernel_TREADY_int() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln29_fu_371_p2.read(), ap_const_lv1_0) && 
         !(esl_seteq<1,1,1>(icmp_ln29_fu_371_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, stream_kernel_TVALID_int.read())))) {
        stream_kernel_TREADY_int = ap_const_logic_1;
    } else {
        stream_kernel_TREADY_int = ap_const_logic_0;
    }
}

void conv2d::thread_stream_output_TDATA_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read()))) {
        stream_output_TDATA_blk_n = stream_output_TREADY_int.read();
    } else {
        stream_output_TDATA_blk_n = ap_const_logic_1;
    }
}

void conv2d::thread_stream_output_TLAST_int() {
    stream_output_TLAST_int =  (sc_logic) (tmp_last_reg_952.read()[0]);
}

void conv2d::thread_stream_output_TVALID() {
    stream_output_TVALID = regslice_both_stream_output_V_data_U_vld_out.read();
}

void conv2d::thread_stream_output_TVALID_int() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read()) && 
         esl_seteq<1,1,1>(stream_output_TREADY_int.read(), ap_const_logic_1))) {
        stream_output_TVALID_int = ap_const_logic_1;
    } else {
        stream_output_TVALID_int = ap_const_logic_0;
    }
}

void conv2d::thread_sub_ln31_fu_365_p2() {
    sub_ln31_fu_365_p2 = (!zext_ln31_1_fu_361_p1.read().is_01() || !zext_ln31_fu_349_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(zext_ln31_1_fu_361_p1.read()) - sc_biguint<5>(zext_ln31_fu_349_p1.read()));
}

void conv2d::thread_sub_ln60_fu_520_p2() {
    sub_ln60_fu_520_p2 = (!zext_ln60_cast_fu_500_p3.read().is_01() || !zext_ln60_2_cast_fu_512_p3.read().is_01())? sc_lv<13>(): (sc_biguint<13>(zext_ln60_cast_fu_500_p3.read()) - sc_biguint<13>(zext_ln60_2_cast_fu_512_p3.read()));
}

void conv2d::thread_sub_ln65_fu_615_p2() {
    sub_ln65_fu_615_p2 = (!zext_ln65_2_fu_611_p1.read().is_01() || !zext_ln65_1_fu_599_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(zext_ln65_2_fu_611_p1.read()) - sc_biguint<5>(zext_ln65_1_fu_599_p1.read()));
}

void conv2d::thread_sub_ln84_fu_715_p2() {
    sub_ln84_fu_715_p2 = (!zext_ln84_cast_fu_695_p3.read().is_01() || !zext_ln84_2_cast_fu_707_p3.read().is_01())? sc_lv<13>(): (sc_biguint<13>(zext_ln84_cast_fu_695_p3.read()) - sc_biguint<13>(zext_ln84_2_cast_fu_707_p3.read()));
}

void conv2d::thread_tmp_8_fu_603_p3() {
    tmp_8_fu_603_p3 = esl_concat<2,2>(m_0_reg_271.read(), ap_const_lv2_0);
}

void conv2d::thread_tmp_fu_353_p3() {
    tmp_fu_353_p3 = esl_concat<2,2>(row_0_reg_191.read(), ap_const_lv2_0);
}

void conv2d::thread_tmp_last_1_fu_388_p1() {
    tmp_last_1_fu_388_p1 =  (sc_lv<1>) (stream_kernel_TLAST_int.read());
}

void conv2d::thread_tmp_last_2_fu_463_p1() {
    tmp_last_2_fu_463_p1 =  (sc_lv<1>) (stream_input_TLAST_int.read());
}

void conv2d::thread_tmp_last_fu_741_p2() {
    tmp_last_fu_741_p2 = (icmp_ln79_reg_934.read() & icmp_ln79_1_fu_736_p2.read());
}

void conv2d::thread_trunc_ln41_fu_421_p1() {
    trunc_ln41_fu_421_p1 = row_1_reg_213.read().range(8-1, 0);
}

void conv2d::thread_trunc_ln43_fu_467_p1() {
    trunc_ln43_fu_467_p1 = col_1_reg_224.read().range(14-1, 0);
}

void conv2d::thread_trunc_ln60_1_fu_508_p1() {
    trunc_ln60_1_fu_508_p1 = row_2_reg_235.read().range(12-1, 0);
}

void conv2d::thread_trunc_ln60_2_fu_551_p1() {
    trunc_ln60_2_fu_551_p1 = col_2_reg_247.read().range(13-1, 0);
}

void conv2d::thread_trunc_ln60_fu_496_p1() {
    trunc_ln60_fu_496_p1 = row_2_reg_235.read().range(7-1, 0);
}

void conv2d::thread_trunc_ln65_1_fu_637_p1() {
    trunc_ln65_1_fu_637_p1 = col_2_reg_247.read().range(14-1, 0);
}

void conv2d::thread_trunc_ln65_fu_581_p1() {
    trunc_ln65_fu_581_p1 = row_2_reg_235.read().range(8-1, 0);
}

void conv2d::thread_trunc_ln84_1_fu_703_p1() {
    trunc_ln84_1_fu_703_p1 = row_3_reg_305.read().range(12-1, 0);
}

void conv2d::thread_trunc_ln84_2_fu_746_p1() {
    trunc_ln84_2_fu_746_p1 = col_3_reg_316.read().range(13-1, 0);
}

void conv2d::thread_trunc_ln84_fu_691_p1() {
    trunc_ln84_fu_691_p1 = row_3_reg_305.read().range(7-1, 0);
}

void conv2d::thread_zext_ln31_1_fu_361_p1() {
    zext_ln31_1_fu_361_p1 = esl_zext<5,4>(tmp_fu_353_p3.read());
}

void conv2d::thread_zext_ln31_2_fu_392_p1() {
    zext_ln31_2_fu_392_p1 = esl_zext<5,2>(col_0_reg_202.read());
}

void conv2d::thread_zext_ln31_fu_349_p1() {
    zext_ln31_fu_349_p1 = esl_zext<5,2>(row_0_reg_191.read());
}

void conv2d::thread_zext_ln40_fu_406_p1() {
    zext_ln40_fu_406_p1 = esl_zext<32,31>(row_1_reg_213.read());
}

void conv2d::thread_zext_ln41_fu_443_p1() {
    zext_ln41_fu_443_p1 = esl_zext<32,31>(col_1_reg_224.read());
}

void conv2d::thread_zext_ln43_cast_fu_425_p3() {
    zext_ln43_cast_fu_425_p3 = esl_concat<8,6>(trunc_ln41_fu_421_p1.read(), ap_const_lv6_0);
}

void conv2d::thread_zext_ln43_fu_476_p1() {
    zext_ln43_fu_476_p1 = esl_zext<64,14>(add_ln43_fu_471_p2.read());
}

void conv2d::thread_zext_ln57_fu_481_p1() {
    zext_ln57_fu_481_p1 = esl_zext<32,31>(row_2_reg_235.read());
}

void conv2d::thread_zext_ln58_fu_536_p1() {
    zext_ln58_fu_536_p1 = esl_zext<32,31>(col_2_reg_247.read());
}

void conv2d::thread_zext_ln60_2_cast_fu_512_p3() {
    zext_ln60_2_cast_fu_512_p3 = esl_concat<12,1>(trunc_ln60_1_fu_508_p1.read(), ap_const_lv1_0);
}

void conv2d::thread_zext_ln60_cast_fu_500_p3() {
    zext_ln60_cast_fu_500_p3 = esl_concat<7,6>(trunc_ln60_fu_496_p1.read(), ap_const_lv6_0);
}

void conv2d::thread_zext_ln65_1_fu_599_p1() {
    zext_ln65_1_fu_599_p1 = esl_zext<5,2>(m_0_reg_271.read());
}

void conv2d::thread_zext_ln65_2_fu_611_p1() {
    zext_ln65_2_fu_611_p1 = esl_zext<5,4>(tmp_8_fu_603_p3.read());
}

void conv2d::thread_zext_ln65_3_fu_633_p1() {
    zext_ln65_3_fu_633_p1 = esl_zext<14,2>(n_0_reg_294.read());
}

void conv2d::thread_zext_ln65_4_fu_657_p1() {
    zext_ln65_4_fu_657_p1 = esl_zext<5,2>(n_0_reg_294.read());
}

void conv2d::thread_zext_ln65_fu_577_p1() {
    zext_ln65_fu_577_p1 = esl_zext<8,2>(m_0_reg_271.read());
}

void conv2d::thread_zext_ln76_fu_671_p1() {
    zext_ln76_fu_671_p1 = esl_zext<32,31>(row_3_reg_305.read());
}

void conv2d::thread_zext_ln77_fu_721_p1() {
    zext_ln77_fu_721_p1 = esl_zext<32,31>(col_3_reg_316.read());
}

void conv2d::thread_zext_ln84_2_cast_fu_707_p3() {
    zext_ln84_2_cast_fu_707_p3 = esl_concat<12,1>(trunc_ln84_1_fu_703_p1.read(), ap_const_lv1_0);
}

void conv2d::thread_zext_ln84_cast_fu_695_p3() {
    zext_ln84_cast_fu_695_p3 = esl_concat<7,6>(trunc_ln84_fu_691_p1.read(), ap_const_lv6_0);
}

void conv2d::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln28_fu_337_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && (esl_seteq<1,1,1>(ap_const_lv1_1, tmp_last_1_fu_388_p1.read()) || 
  esl_seteq<1,1,1>(icmp_ln29_fu_371_p2.read(), ap_const_lv1_1)) && !(esl_seteq<1,1,1>(icmp_ln29_fu_371_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, stream_kernel_TVALID_int.read())))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(icmp_ln29_fu_371_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_last_1_fu_388_p1.read()) && !(esl_seteq<1,1,1>(icmp_ln29_fu_371_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, stream_kernel_TVALID_int.read())))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln40_fu_410_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && (esl_seteq<1,1,1>(ap_const_lv1_1, tmp_last_2_fu_463_p1.read()) || 
  esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln41_fu_447_p2.read())) && !(esl_seteq<1,1,1>(icmp_ln41_fu_447_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_0, stream_input_TVALID_int.read())))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(icmp_ln41_fu_447_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_last_2_fu_463_p1.read()) && !(esl_seteq<1,1,1>(icmp_ln41_fu_447_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_0, stream_input_TVALID_int.read())))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 32 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln57_fu_485_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state17;
            } else {
                ap_NS_fsm = ap_ST_fsm_state7;
            }
            break;
        case 64 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln58_fu_540_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_state8;
            }
            break;
        case 128 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln63_fu_565_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state7;
            } else {
                ap_NS_fsm = ap_ST_fsm_state9;
            }
            break;
        case 256 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln64_fu_621_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state8;
            } else {
                ap_NS_fsm = ap_ST_fsm_state10;
            }
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 65536 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()) && esl_seteq<1,1,1>(regslice_both_stream_output_V_data_U_apdone_blk.read(), ap_const_logic_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln76_fu_675_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()) && esl_seteq<1,1,1>(regslice_both_stream_output_V_data_U_apdone_blk.read(), ap_const_logic_0) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln76_fu_675_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state18;
            } else {
                ap_NS_fsm = ap_ST_fsm_state17;
            }
            break;
        case 131072 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln77_fu_725_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state17;
            } else {
                ap_NS_fsm = ap_ST_fsm_state19;
            }
            break;
        case 262144 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read()) && esl_seteq<1,1,1>(stream_output_TREADY_int.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state20;
            } else {
                ap_NS_fsm = ap_ST_fsm_state19;
            }
            break;
        case 524288 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read()) && esl_seteq<1,1,1>(stream_output_TREADY_int.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state18;
            } else {
                ap_NS_fsm = ap_ST_fsm_state20;
            }
            break;
        default : 
            ap_NS_fsm =  (sc_lv<20>) ("XXXXXXXXXXXXXXXXXXXX");
            break;
    }
}

void conv2d::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"stream_kernel_TDATA\" :  \"" << stream_kernel_TDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"stream_kernel_TVALID\" :  \"" << stream_kernel_TVALID.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"stream_kernel_TREADY\" :  \"" << stream_kernel_TREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"stream_kernel_TLAST\" :  \"" << stream_kernel_TLAST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"stream_input_TDATA\" :  \"" << stream_input_TDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"stream_input_TVALID\" :  \"" << stream_input_TVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"stream_input_TREADY\" :  \"" << stream_input_TREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"stream_input_TLAST\" :  \"" << stream_input_TLAST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"stream_output_TDATA\" :  \"" << stream_output_TDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"stream_output_TVALID\" :  \"" << stream_output_TVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"stream_output_TREADY\" :  \"" << stream_output_TREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"stream_output_TLAST\" :  \"" << stream_output_TLAST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_AWVALID\" :  \"" << s_axi_AXILiteS_AWVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_AWREADY\" :  \"" << s_axi_AXILiteS_AWREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_AWADDR\" :  \"" << s_axi_AXILiteS_AWADDR.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_WVALID\" :  \"" << s_axi_AXILiteS_WVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_WREADY\" :  \"" << s_axi_AXILiteS_WREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_WDATA\" :  \"" << s_axi_AXILiteS_WDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_WSTRB\" :  \"" << s_axi_AXILiteS_WSTRB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_ARVALID\" :  \"" << s_axi_AXILiteS_ARVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_ARREADY\" :  \"" << s_axi_AXILiteS_ARREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_ARADDR\" :  \"" << s_axi_AXILiteS_ARADDR.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_RVALID\" :  \"" << s_axi_AXILiteS_RVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_RREADY\" :  \"" << s_axi_AXILiteS_RREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_RDATA\" :  \"" << s_axi_AXILiteS_RDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_RRESP\" :  \"" << s_axi_AXILiteS_RRESP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_BVALID\" :  \"" << s_axi_AXILiteS_BVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_BREADY\" :  \"" << s_axi_AXILiteS_BREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_BRESP\" :  \"" << s_axi_AXILiteS_BRESP.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

