# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Vincent/Desktop/cnn-on-pynq-z2/vivado_proj_v2/vivado_proj_v2.srcs/sources_1/bd/design_1/ip/design_1_auto_us_4/design_1_auto_us_4.xci
# IP: The module: 'design_1_auto_us_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Vincent/Desktop/cnn-on-pynq-z2/vivado_proj_v2/vivado_proj_v2.srcs/sources_1/bd/design_1/ip/design_1_auto_us_4/design_1_auto_us_4_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_auto_us_4'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Vincent/Desktop/cnn-on-pynq-z2/vivado_proj_v2/vivado_proj_v2.srcs/sources_1/bd/design_1/ip/design_1_auto_us_4/design_1_auto_us_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_auto_us_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/Vincent/Desktop/cnn-on-pynq-z2/vivado_proj_v2/vivado_proj_v2.srcs/sources_1/bd/design_1/ip/design_1_auto_us_4/design_1_auto_us_4.xci
# IP: The module: 'design_1_auto_us_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Vincent/Desktop/cnn-on-pynq-z2/vivado_proj_v2/vivado_proj_v2.srcs/sources_1/bd/design_1/ip/design_1_auto_us_4/design_1_auto_us_4_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_auto_us_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Vincent/Desktop/cnn-on-pynq-z2/vivado_proj_v2/vivado_proj_v2.srcs/sources_1/bd/design_1/ip/design_1_auto_us_4/design_1_auto_us_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_auto_us_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
